group: dynamic_graph_benchmark
task:
  - dynamic_graph_benchmark_coloring_direct
  - dynamic_graph_benchmark_coloring_disguise
  - dynamic_graph_benchmark_directed_connectivity_direct
  - dynamic_graph_benchmark_directed_connectivity_disguise
